on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm i
      - run: npm run build-all
      - run: npm run e2e
